# Site Information
site_name: lip0041 -- 说服下自己
site_author: isobung

# Contents
nav:
  - 简介:
    - Getting Started: index.md
  - Solutions:
    - Advanced:
      - A1001: pat/ab-format.md
      - A1002: pat/ab-for-polynomials.md
      - A1004: pat/counting-leaves.md
      - A1005: pat/spell-it-right.md
      - A1006: pat/sign-in-and-sign-out.md
      - A1009: pat/product-of-polynomials.md
      - A1011: pat/world-cup-betting.md
      - A1014: pat/waiting-in-line.md
      - A1019: pat/general-palindromic-number.md
      - A1020: pat/tree-traversals.md
      - A1022: pat/digital-library.md
      - A1031: pat/hello-world-for-u.md
      - A1032: pat/sharing.md
      - A1035: pat/password.md
      - A1036: pat/boys-vs-girls.md
      - A1039: pat/course-list-for-student.md
      - A1042: pat/shuffing-machine.md
      - A1046: pat/shortest-distance.md
      - A1047: pat/student-list-for-course.md
      - A1051: pat/pop-sequence.md
      - A1052: pat/linked-list-sorting.md
      - A1054: pat/the-dominant-color.md
      - A1056: pat/mice-and-rice.md
      - A1060: pat/are-the-equal.md
      - A1061: pat/dating.md
      - A1063: pat/set-similarity.md
      - A1065: pat/ab-and-c-64bit.md
      - A1071: pat/speech-patterns.md
      - A1073: pat/scientific-notation.md
      - A1074: pat/reversing-linked-list.md
      - A1077: pat/kuchiguse.md
      - A1082: pat/read-number-in-chinese.md
      - A1086: pat/tree-traversals-again.md
      - A1091: pat/acute-stroke.md
      - A1097: pat/deduplication-on-a-linked-list.md
      - A1100: pat/mars-numbers.md
      - A1102: pat/invert-a-binary-tree.md
      - A1103: pat/integer-factorization.md
      - A1109: pat/group-photo.md
    - mooc:
      - PA2: thu/proper-rebuild.md
      - PA1: thu/light-house.md
  - Notes:
    - Program Languages: 
      - C++: cpp/cpp.md

# Theme
theme:
  name: material
  custom_dir: docs/overrides
  language: en
  # dark and light mode-switch 
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: icons/penguin.png
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Customization
extra:
  pagetime: 'on'
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lip0041

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


